name: Docker Testing and Push
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@main

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Run test
        run: |
          script -e -c "./test.sh"

  publish:
    runs-on: "ubuntu-24.04"
    if: github.ref == 'refs/heads/main' # only run when pushed to main branch
    permissions: write-all
    needs: test
    steps:
      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push red-dawn-network/quartermaster
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/red-dawn-network/quartermaster:latest,ghcr.io/red-dawn-network/quartermaster:${{ github.sha }}
